web/router.ex
defmodule Survey.Router do
  use Survey.Web, :router
  @logformat "%u %t %m \"%U\" %>s %b %D"

  pipeline :browser do
    plug ParamSession
    plug EnsureLti
    plug Plug.AccessLog,
      format: @logformat,
      file: "log/access_log"
    plug :accepts, ["html"]
    plug :fetch_flash
    plug EnsureRegistered
    plug EnsureSIG
  end

  # don't ensure registered, only for new users to register
  pipeline :register do
    plug ParamSession
    plug EnsureLti
    plug Plug.AccessLog,
      format: @logformat,
      file: "log/access_log"
    plug :accepts, ["html"]
    plug :fetch_flash
  end

  pipeline :admin do
    plug Plug.Session,
      store: :cookie,
      key: "_test_key",
      signing_salt: "LMvTyOc2"
    plug :fetch_session
    plug VerifyAdmin
    plug Plug.AccessLog,
      format: @logformat,
      file: "log/access_log"
    plug :fetch_flash
    plug :accepts, ["html"]
  end

  pipeline :public do
    plug Plug.Session,
      store: :cookie,
      key: "_test_key",
      signing_salt: "LMvTyOc2"
    plug :fetch_session
    plug Plug.AccessLog,
      format: @logformat,
      file: "log/access_log"
    plug :fetch_flash
    plug :accepts, ["html"]
  end

  scope "/", Survey do
    pipe_through :browser

    # survey
    get "/survey", SurveyController, :index
    post "/survey", SurveyController, :index
    post "/survey/submit", SurveyController, :submit
    post "/survey/submitajax", SurveyController, :submitajax

    # exit survey
    get "/exit", SurveyController, :exit
    post "/exit", SurveyController, :exit
    post "/survey/submit-exit", SurveyController, :submit_exit
    post "/survey/submitajax-exit", SurveyController, :submitajax_exit

    # resource submission/review
    post "/resource/add", ResourceController, :add
    get "/resource/add", ResourceController, :add

    post "/resource/review", ResourceController, :review
    post "/resource/review/submit", ResourceController, :review_submit
    get "/resource/review", ResourceController, :review
    post "/resource/review/:id", ResourceController, :review
    get "/resource/review/:id", ResourceController, :review
    post "/resource/check_url", ResourceController, :check_url

    post "/resource/tag-cloud", ResourceController, :tag_cloud
    post "resource/list", ResourceController, :list
    get "/resource/tag-cloud", ResourceController, :tag_cloud
    get "resource/list", ResourceController, :list


    # issue #1 in plug_lti made it impossible to verify paths with
    # wildcard routes, thus the silly pattern below. Fixed in upcoming version.

    # reflection
    post "/reflection/submission", ReflectionController, :submit
    post "/reflection", ReflectionController, :index
    get "/reflection", ReflectionController, :index
    post "/reflectionb", ReflectionController, :index_b
    get "/reflectionb", ReflectionController, :index_b
    post "/reflectionc", ReflectionController, :index_c
    get "/reflectionc", ReflectionController, :index_c
    post "/reflectiond", ReflectionController, :index_d
    get "/reflectiond", ReflectionController, :index_d
    post "/reflectione", ReflectionController, :index_e
    get "/reflectione", ReflectionController, :index_e
    post "/reflectionf", ReflectionController, :index_f
    get "/reflectionf", ReflectionController, :index_f
    get "/reflection/:id", ReflectionController, :index
    post "/reflection/:id", ReflectionController, :index

    # sig
    get "/user/select_sig_freestanding", UserController,
      :select_sig_freestanding
    post "/user/select_sig_freestanding", UserController,
      :select_sig_freestanding

    # review lesson designs
    # entrypoint:
    get "/lessondesigns/sidebar", LessonplanController, :sidebar
    post "/lessondesigns/sidebar", LessonplanController, :sidebar

    get "/lessondesigns/overview", LessonplanController, :overview
    post "/lessondesigns/overview", LessonplanController, :overview
    get "/lessondesigns/:id", LessonplanController, :detail
    post "/lessondesigns/:id", LessonplanController, :detail

    # commentstream
    post "/commentstream/submit", CommentstreamController, :submit

    # assessment
    post "/assessment", ReflectionController, :assessment
    get "/assessment", ReflectionController, :assessment
    post "/assessmentb", ReflectionController, :assessment_b
    get "/assessmentb", ReflectionController, :assessment_b
    post "/assessmentc", ReflectionController, :assessment_c
    get "/assessmentc", ReflectionController, :assessment_c
    post "/assessmentd", ReflectionController, :assessment_d
    get "/assessmentd", ReflectionController, :assessment_d
    post "/assessmente", ReflectionController, :assessment_e
    get "/assessmente", ReflectionController, :assessment_e
    post "/assessmentf", ReflectionController, :assessment_f
    get "/assessmentf", ReflectionController, :assessment_f
    post "/assessment/submit", ReflectionController, :assessment_submit
    get "/assessment/submit", ReflectionController, :assessment_submit
    post "/assessment/:id", ReflectionController, :assessment
    get "/assessment/:id", ReflectionController, :assessment

    # designgroups
    post "/design_groups/add_idea", DesignGroupController, :add_idea
    get "/design_groups/add_idea", DesignGroupController, :add_idea

    post "/design_groups/select", DesignGroupController, :select
    get "/design_groups/select", DesignGroupController, :select
    get "/design_groups/select/sidebar", DesignGroupController, :select_sidebar
    get "/design_groups/select/detail/:id", DesignGroupController, :select_detail
    get "/design_groups/select/overview", DesignGroupController, :overview
    post "/design_groups/select/submit", DesignGroupController, :submit

    get "/design_groups/comments", DesignGroupController, :comments
    post "/design_groups/comments", DesignGroupController, :comments

    post "/design_groups/submit_edit", DesignGroupController, :submit_edit

    # collaborative workbench
    post "/collab", CollabController, :index
    get "/collab", CollabController, :index
    post "/collab/leave", CollabController, :leave
    post "/collab/email", CollabController, :email

    # email notification control
    get "/email/unsubscribe/all", EmailController, :unsubscribe
    get "/email/unsubscribe/collab", EmailController, :unsubscribe_collab

    # review
    post "/review/submit", ReviewController, :submit
    get "/review/cancel", ReviewController, :cancel
    post "/review/cancel", ReviewController, :cancel
    post "/review/:id", ReviewController, :index
    get "/review/:id", ReviewController, :index

    # wiki review
    post "/wiki-review", ReviewController, :wiki
    get "/wiki-review", ReviewController, :wiki
    post "/wiki-review/submit", ReviewController, :wiki_submit
    post "/gallerywalk/detail/:id", ReviewController, :gallerywalk_detail
    get "/gallerywalk/detail/:id", ReviewController, :gallerywalk_detail
    get "/gallerywalk/initial", ReviewController, :gallerywalk_initial
    post "/gallerywalk/initial", ReviewController, :gallerywalk_initial
    get "/gallerywalk", ReviewController, :gallerywalk
    post "/gallerywalk", ReviewController, :gallerywalk

    # brainstorm
    post "/brainstorm", BrainstormController, :index
    get "/brainstorm", BrainstormController, :index
    post "/brainstormb", BrainstormController, :index_b
    get "/brainstormb", BrainstormController, :index_b
    post "/live_a", BrainstormController, :live_a
    get "/live_a", BrainstormController, :live_a
    post "/live_b", BrainstormController, :live_b
    get "/live_b", BrainstormController, :live_b
  end

  scope "/", Survey do
    pipe_through :register
    get "/user/register", UserController, :index
    post "/user/register/submit", UserController, :submit
    post "/user/get_tags", UserController, :get_tags
    get "/user/select_sig", UserController, :select_sig
    post "/user/select_sig/submit", UserController, :select_sig_submit
  end

  scope "/admin", Survey do
    pipe_through :admin
    get "/report", ReportController, :index
    get "/report/text/:qid", ReportController, :fulltext
    post "/report/text/:qid", ReportController, :fulltext
    get "/report/tags", ReportController, :tags
    get "/report/exit", AdminController, :exit
    get "/report/exit/text/:qid", AdminController, :exit_text
    get "/report/resource", ResourceController, :report
    get "/report/designgroups", DesignGroupController, :report
    get "/report/designgroups/activity", AdminController, :group_activity
    get "/resource/preview", ResourceController, :preview
    get "/report/reflections", AdminController, :reflections
    get "/report/reflections/:id", AdminController, :reflections
    get "/report/reflections/text/:id/:qid", AdminController, :fulltext
    post "/report/reflections/text/:id/:qid", AdminController, :fulltext

    get "/collab/:id", CollabController, :admin
    get "/cohorts", AdminController, :cohorts

    get "/email/send_wk1", AdminController, :wk1
    get "/email/send_wk2", AdminController, :wk2
    # user info/debug
    get "/userinfo", UserController, :info
    post "/userinfo", UserController, :info

  end

  scope "/", Survey do
    pipe_through :public

    get "/email/:hash", EmailController, :redirect
    post "/email/:hash", EmailController, :redirect

    post "/public/gallerywalk/detail/:id", ReviewController, :gallerywalk_detail
    get "/public/gallerywalk/detail/:id", ReviewController, :gallerywalk_detail
    get "/public/gallerywalk/initial", ReviewController, :gallerywalk_initial
    post "/public/gallerywalk/initial", ReviewController, :gallerywalk_initial
    get "/public/gallerywalk", ReviewController, :gallerywalk_public
    post "/public/gallerywalk", ReviewController, :gallerywalk_public
  end
end

web/controllers/review_controller.ex
defmodule Survey.ReviewController do
  use Survey.Web, :controller
  alias Survey.DesignGroup
  alias Survey.Review
  import Ecto.Query
  require Ecto.Query
  alias Survey.Repo
  require Logger
  import Prelude
  @form Survey.HTML.Survey.gen_survey("data/review.txt", :f)
  @form2 Survey.HTML.Survey.gen_survey("data/review2.txt", :f)
  @form3 Survey.HTML.Survey.gen_survey("data/review3.txt", :f)

  def index(conn, params = %{"id" => id}) do
    group = DesignGroup.get(id)
    if !group.id do
      html conn, "This design group does not exist"
    else
      conn
      |> put_layout(false)
      |> render "index.html", group: group, form: @form
    end
  end

  def cancel(conn, _) do
    ParamSession.redirect(conn, "/design_groups/select")
  end

  def submit(conn, params) do
    %Review{
      user_id: conn.assigns.user.id,
      design_group_id: string_to_int_safe(params["id"]),
      week: 1,
      review: params["f"]
    } |> Repo.insert!
    Survey.Grade.submit_grade(conn, "review_wk1", 1.0)
    ParamSession.redirect(conn, "/design_groups/select?submitted=true")
  end

  def wiki(conn, params) do
    user = conn.assigns.user
    submitted = if params["submitted"], do: true, else: false
    case DesignGroup.get_random_wiki(user.sig_id) do
      nil ->
        html conn, "No design groups ready in your SIG yet. Please
        try again later."
      {group, html} ->
        conn
        |> put_layout(false)
        |> render "index_wiki.html", form: @form3, html: html, group: group,
          submitted: submitted
    end
  end

  def wiki_submit(conn, params) do
    Logger.info("Submitted review for week 4")
    %Review{
      user_id: conn.assigns.user.id,
      design_group_id: string_to_int_safe(params["id"]),
      week: 4,
      review: params["f"]
    } |> Repo.insert!
    Survey.Grade.submit_grade(conn, "review_wk4", 1.0)
    ParamSession.redirect(conn, "/wiki-review?submitted=true")
  end

  def gallerywalk(conn, params, logged_in \\ true) do
    groupids = [10, 70, 114, 153, 216, 294, 2, 13, 18, 28, 75, 108, 121, 157, 202, 213, 21, 56,
      149, 170, 63, 181, 188, 231, 240]
    groups = (from f in Survey.DesignGroup, where: f.id in ^groupids)
              |> Survey.Repo.all
              |> Prelude.Map.group_by([:sig_id])
    sigs = Survey.SIG.map

    conn
    |> put_layout(false)
    |> render "gallerywalk.html", groups: groups, sigs: sigs, logged_in: logged_in
  end

  def gallerywalk_public(conn, params) do
    gallerywalk(conn, params, false)
  end

  def gallerywalk_detail(conn, %{"id" => id}) do
    group = Survey.DesignGroup.get(id)
    htmlstr = Survey.Cache.get(group.wiki_cache_id)
    comments = Survey.Commentstream.get("gallerywalk", id)
    title = group.title
    conn
    |> render "gallerywalk_detail.html", htmlstr: htmlstr, comments: comments, title: title
  end

  def gallerywalk_initial(conn, _) do
    html conn, "<h3>Please select a group on the left to view their design project, and leave at least one comment to get graded</h3>"
  end
end

web/views/review_view.ex
defmodule Survey.ReviewView do
  use Survey.Web, :view
end

web/templates/review/gallerywalk.html.eex
<!doctype html>
<html class="no-js" lang="en-us">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Gallery Walk</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <!-- Place favicon.ico in the root directory -->

        <script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
        <link rel="stylesheet" href="/css/normalize.css">

        <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="/css/jquery-ui-collab.css">
        <link rel="stylesheet" href="/css/reset.css">
        <link rel="stylesheet" href="/css/review-main.css">
        <link rel="stylesheet" href="/css/review-chat.css">


        <script src="/js/modernizr-2.8.3.min.js"></script>
        <script src="/js/lodash.js"></script>
        <script src="/js/review.js"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
<div class="top">
<h2>Gallery Walk</h2>
<h1>INQ101x - Teaching with Technology and Inquiry</h1>
</div>


<!-- --------------------------------------------------------- --!>
<div class="sidebar" name="sidebar">
  <div class='blocks'>
  <%= for {sig, sig_groups} <- @groups do %>
    <h1><%= @sigs[sig] %></h1>
    <ul>
    <%= for group <- List.flatten(sig_groups) do %>
      <li style='margin: 8px'><a href=
      <%= if @logged_in do %>
      '<%= ParamSession.gen_url(@conn, "gallerywalk/detail/#{group.id}") %>'
      <%= else %>
      '<%= "gallerywalk/detail/#{group.id}" %>'
    <% end %>
      target='iframe'><%= group.title %></a></li>
    <% end %>
    </ul>
  <% end %>
</div>
</div>
<!-- --------------------------------------------------------- --!>

<div class="maincontent">
<iframe name="iframe" class="iframe" style='width: 100%; height: 100%' src="/public/gallerywalk/initial">
</div>
</body>
</html>

web/templates/review/gallerywalk_detail.html.eex
<div><a href="#comments">Jump to comments</a></div>
<style>
h1 { font-size: 28px !important; }
h2 { font-size: 22px !important; } </style>
<h1><%= @title %></h1>
<%= raw @htmlstr %>
<hr>
<%= render Survey.CommentstreamView, "_comments.html", comments: @comments, conn: @conn %>

web/templates/review/index.html.eex
<!doctype html>
<html class="no-js" lang="en-us">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Review Design Group</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <!-- Place favicon.ico in the root directory -->

        <script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
        <link rel="stylesheet" href="/css/normalize.css">
        
        <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="/css/jquery-ui-collab.css">
        <link rel="stylesheet" href="/css/reset.css">
        <link rel="stylesheet" href="/css/review-main.css">
        <link rel="stylesheet" href="/css/review-chat.css">

        
        <script src="/js/modernizr-2.8.3.min.js"></script>
        <script src="/js/lodash.js"></script>
        <script src="/js/review.js"></script>
 <script>
   session = '<%= raw ParamSession.gen_cookie(@conn) %>'
     $('document').ready(function() {
    $( "#tabs" ).tabs();
    $("#tabs").show();
  })
        </script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
<div class="top">
<h2>Review Design Group</h2>
<h1>INQ101x - Teaching with Technology and Inquiry</h1>
</div>

<div class="content">

<div class="groupname">

    <h3 class="title"><%= @group.title %></h3>


</div>
<!-- --------------------------------------------------------- --!>
<div class="sidebar" name="sidebar">
  <span id="top"></span>
    <div class="container">
      <div class="header">
    </div></div>
  <div class='blocks'>
              <%= form_for @conn, review_path(@conn, :submit), [name: :search], fn _ -> %>
                <%= raw ParamSession.form_session @conn %>
                <%= raw @form %>
                <input type=hidden name=id value=<%= @group.id %>>
<div class='stepsController submit right'><a href='#'>Submit your comments</a></div>
<div class='stepsController cancel right'><a href='#'>Cancel and return to list</a></div>
   <% end %>
</div>
</div>
<!-- --------------------------------------------------------- --!>

<div class="maincontent">
<div id="tabs" class="ui-tabs ui-widget ui-widget-content" style="display: none;">

<!--To add new tabs, simply add a <li> in this list, using the same structure and following the link sequence. Then, add a new <iframe>, also using the same structure.--> 

    <ul style="padding: 0; margin: 0;" class="ui-tabs-nav ui-helper-reset ui-helper-clearfix">
        <li class="context-tab ui-state-default"><a href="#ui-tabs-1">Design Group description</a></li>
        <li class="context-tab ui-state-default"><a href="#ui-tabs-2">Resources</a></li>
    </ul>
</form>


                    <div id="ui-tabs-1"> <iframe id="detail_iframe" src="<%= ParamSession.gen_url(@conn, design_group_path(@conn, :select_detail, @group.id, review: true)) %>"></iframe></div>

<div id="ui-tabs-2"> <iframe src="<%= ParamSession.gen_url(@conn, "/resource/list") %>"></iframe></div>

</div>
</div>


</html>

web/templates/review/index_wiki.html.eex
<!doctype html>
<html class="no-js" lang="en-us">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Review Design Group</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <!-- Place favicon.ico in the root directory -->

        <script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
        <link rel="stylesheet" href="/css/normalize.css">

        <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="/css/jquery-ui-collab.css">
        <link rel="stylesheet" href="/css/reset.css">
        <link rel="stylesheet" href="/css/review-main.css">
        <link rel="stylesheet" href="/css/review-chat.css">


        <script src="/js/modernizr-2.8.3.min.js"></script>
        <script src="/js/lodash.js"></script>
        <script src="/js/review.js"></script>
 <script>
   session = '<%= raw ParamSession.gen_cookie(@conn) %>'
     $('document').ready(function() {
    $( "#tabs" ).tabs();
    $("#tabs").show();
  })
        </script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
<div class="top">
<h2>Review Design Group</h2>
<h1>INQ101x - Teaching with Technology and Inquiry</h1>
</div>

<div class="content">

<div class="groupname">

    <h3 class="title"><%= @group.title %></h3>

    <div class='stepsController cancel right'><a href='/wiki-review?session=<%= ParamSession.gen_cookie(@conn) %>'>Reroll and review another group</a></div>

</div>
<!-- --------------------------------------------------------- --!>
<div class="sidebar" name="sidebar">
  <span id="top"></span>
    <div class="container">
      <div class="header">
    </div></div>
  <div class='blocks'>
  <%= form_for @conn, review_path(@conn, :wiki_submit),
  [name: :search, target: "_parent"], fn _ -> %>
                <%= raw ParamSession.form_session @conn %>
                <%= raw @form %>
                <input type=hidden name=id value=<%= @group.id %>>
<div class='stepsController submit right'><a href='#'>Submit your comments</a></div>
   <% end %>
</div>
</div>
<!-- --------------------------------------------------------- --!>

<div class="maincontent">

<%= if @submitted == true do %>
    <p class='alert alert-success'>
    Thank you for submitting a review, you have already been graded. Feel free to review more groups.</p><% end %>
            <h3>Topics</h3><p id='topics'><span class="category"><%= @group.description && @group.description["topics"] %></span></p>
                <h3>Short description of the basic inquiry approach</h3>
                <p id='description'><%= @group.description && @group.description["description"] %></p>

                <h3>How can technology help students to build their own ideas and collaborate with peers?</h3>
                <p id='howtech'><%= @group.description && @group.description["howtech"] %></p>
            <hr>

<h3>Wiki content</h3>
<%= raw @html || "" %>
</body>
</html>

web/templates/review/overview.html.eex
<!doctype html>
<html class="no-js" lang="en-us">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <!-- Place favicon.ico in the root directory -->

        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/reset.css">
        <link rel="stylesheet" href="css/overview.css">
        <script src="js/vendor/modernizr-2.8.3.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

<div>
<p>
On the left are some lesson designs created by students in a University of Toronto course with a similar theme to this MOOC. We recognize that these lessons are not a perfect fit for every classroom, but they should provide an interesting opportunity for critique and reflection. These are different from the WISE activity, which was pre-made, tested, and packaged together with a technology environment.  These lessons use off-the-shelf technologies, and were thoughtfully design to engage students in working with ideas and collaborating with peers. While they were designed for a particular age level, we suggest that, with some adaptations, many could be applied for a younger or older audience. Please choose one or more lesson, and add a comment about how you feel the lesson would succeed with your students, or how it could be modified to improve its effectiveness.  
</p>
</div>

        <!--script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script-->
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.3.min.js"><\/script>')</script>
        <script src="js/plugins.js"></script>
        <script src="js/masked-input.js"></script>
        <script src="js/main.js"></script>
    </body>
</html>